---
title: ""
---

<style type="text/css">
<!-- div#TOC li { -->
<!--     list-style:none; -->
<!--     background-image:none; -->
<!--     background-repeat:none; -->
<!--     background-position:0;  -->
<!-- } -->
 .book .book-body .page-inner  { 
    max-width: 1400px; 
 <!-- width: 120%;  -->
 } 
 .column-left {
  float: left;
  width: 49.7%;
}
.column-right{
 float: right;
  width: 49.7%;
}
.col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
h1 {
  color: #033c73;
   font-size: 30px;
}
h1.title {
  color: #033c73;
}
h2 {
  color: #033c73;
  font-size: 24px;
}
h3 {
   color: #033c73;
   font-size: 18px;
}
h4 {
   color: #022f5a;
}
h5 {
  color: #033c73;
}
h6 {
   color: #033c73;
}
body{ 
  font-size: 14px;
}
p.caption {
  font-size: 0.9em;
  font-style: italic;
  color: grey;
  margin-right: 10%;
  margin-left: 10%;  
  text-align: justify;
} 
.navbar{
  background-color: #428BCA; 
  border-color: #428BCA;
}

</style>

## About me

I am interested in sciences, mostly in biology and computer sciences.


## Education

I am from Paris, France.

I graduated from MsC [GENIOMHE](https://www.universite-paris-saclay.fr/formation/master/bio-informatique/m2-genomics-informatics-and-mathematics-health-and-environment) in bioinformatics in [Université d'Evry](https://www.univ-evry.fr/accueil.html). 

I spent two years in a laboratory in immunology [i3 laboratory](https://i3-immuno.fr/en/) as a research engineer in metagenomics.





